name: selenium-automationexercise CI

on:
  push:
  schedule:
    - cron: '30 18 * * *'  # Runs every day at 6:30 PM UTC

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          choco install maven -y  # Install Maven via Chocolatey
          mvn -v  # Verify Maven installation

      - name: Run Selenium TestNG Tests
        run: mvn clean test  # Clean and run the tests

      #- name: Upload Test Reports
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: test-results
      #    path: test-output  # Path to your test results folder (adjust if different)
