name: Selenium TestNG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 18 * * *'  # Runs at 6:30 PM every day (UTC)

jobs:
  selenium-tests:
    runs-on: windows-latest  # Runs on a Windows environment

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Maven via Chocolatey
      - name: Install Maven
        run: choco install maven -y

      - name: Clean Maven Cache and Settings
        run: |
          del /f /q %USERPROFILE%\.m2\repository\*  # Remove local repository cache
          del /f /q %USERPROFILE%\.m2\settings.xml  # Remove global settings.xml file
          del /f /q %USERPROFILE%\.m2\settings-security.xml  # Remove any encrypted password config

      - name: Set up Maven settings.xml with no repository credentials
        run: |
          echo ^<settings^> > %USERPROFILE%\.m2\settings.xml
          echo ^<mirrors^> >> %USERPROFILE%\.m2\settings.xml
          echo ^<mirror^> >> %USERPROFILE%\.m2\settings.xml
          echo ^<id^>central^</id^> >> %USERPROFILE%\.m2\settings.xml
          echo ^<url^>https://repo.maven.apache.org/maven2^</url^> >> %USERPROFILE%\.m2\settings.xml
          echo ^</mirror^> >> %USERPROFILE%\.m2\settings.xml
          echo ^</mirrors^> >> %USERPROFILE%\.m2\settings.xml
          echo ^</settings^> >> %USERPROFILE%\.m2\settings.xml

      - name: Run Selenium TestNG Tests
        run: mvn clean test -X  # Clean and run the tests with debug output

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
